### ISSUE TITLE
Plenty of build failures in 3.1.3

### ISSUE THREAD

**Issue by svenstaro** [389ds/389-ds-base#6921]
**Issue Description**
I don't really have time to look into this in detail but there are plenty of error during compilation that seem to be some kind of incompatibility. Full log attached.

```
glibc 2.42
gcc 15.1
```

Some excerpts:
```
ldap/servers/slapd/back-ldbm/filterindex.c:505:25: error: too many arguments to function 'mrINDEX'; expected 0, have 1
  505 |                         mrINDEX(pb) ||

ldap/servers/slapd/back-ldbm/ldbm_attr.c:81:32: error: passing argument 2 of 'avl_free' from incompatible pointer type [-Wincompatible-pointer-types]
   81 |     avl_free(inst->inst_attrs, attrinfo_internal_delete);

ldap/servers/slapd/back-ldbm/ldbm_attr.c:271:35: error: too many arguments to function 'syntax_validate_fn'; expected 0, have 1
  271 |                         if ((rc = syntax_validate_fn(&bv))) {
```

**Package Version and Platform:**
 - Platform: Arch Linux
 - Package and version: 3.1.3

[389-ds-base-3.1.2-1-x86_64-build.log](https://github.com/user-attachments/files/21555546/389-ds-base-3.1.2-1-x86_64-build.log)

**Comment by vashirov** [comment]
Hi @svenstaro,
you mentioned version 3.1.3, but provided a log for 3.1.2.
From your attached log:
```
configure: This is configure for 389-ds-base 3.1.2
```


In 3.1.3 we fixed these failures with GCC-15 in https://github.com/389ds/389-ds-base/pull/6536

**Comment by svenstaro** [comment]
Whoops! Sorry for the noise, I confused build boxes. Packaging while too sleep is not a good idea.
