### ISSUE TITLE
Invalid integer to pointer conversion

### ISSUE THREAD

**Issue by Firstyear** [389ds/389-ds-base#5484]
**Issue Description**
```
                                         ^
/home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3205:57: error: incompatible integer to pointer conversion passing 'int64_t' (aka 'long') to parameter of type 'void *' [-Wint-conversion]
    return __sync_bool_compare_and_swap_8((void**)addr, (int64_t)old, (int64_t)(new));
                                                        ^~~~~~~~~~~~
/home/william/development/389ds/ds/ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3205:71: error: incompatible integer to pointer conversion passing 'int64_t' (aka 'long') to parameter of type 'void *' [-Wint-conversion]
    return __sync_bool_compare_and_swap_8((void**)addr, (int64_t)old, (int64_t)(new));
                                                                      ^~~~~~~~~~~~~~
```

Perhaps there is one too many derefs or similar here? Seems to be introduced by e0db9ec157

**Comment by Firstyear** [comment]
Hey @progier389 would you be able to look at this?

**Comment by progier389** [comment]
Hi @Firstyear,
I think it is an architecture or compiler dependent issue 
because on my machine, I got the error if I remove the cast to int64_t
```
/home/progier/sb/i5490/tst/source/389-ds-base/ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3205:57: warning: passing argument 2 of '__sync_bool_compare_and_swap_8' makes integer from pointer without a cast [-Wint-conversion]
 3205 |     return __sync_bool_compare_and_swap_8((void**)addr, old, new);
      |                                                         ^~~
      |                                                         |
      |                                                         volatile void *
```
And I see `/usr/include/clang/Basic/Builtins.def:BUILTIN(__sync_bool_compare_and_swap_8, "bLLiD*LLiLLi.", "tn")`
    so 2nd and 3rd parameters are supposed to be long long (aka int64_t)
But in your case, according to the the error messages,  it expects a void* ...

So I guess we need to add some #ifdef
Do you know if it is related to hardware (i.e x64 versus arm ?) or to compiler ( GCC versus Clang ?)
Do you know which one ?  Maybe #ifdef CPU_arm ?
Perhaps you should try
```
#ifdef CPU_arm
    return __sync_bool_compare_and_swap_8((void**)addr, old, new);
#else
    return __sync_bool_compare_and_swap_8((void**)addr, (int64_t)old, (int64_t)(new));
#endif
```
  ( Sorry, I do not have any ARM hardware so it is difficult for me to handle that issue without your help. )

**Comment by Firstyear** [comment]
I think the problem is that void * and int64_t are not interchangeable in compliers/C. You are using the function as:

```
WriterQueueData_t *slot = NULL;

while (!cas_pt(&ctx->writerq.list, slot, NULL))
```

These are *pointers* you are attempting to compare exchange, not int64_t. It's not actually valid to do this because pointer width on a platform may not match int64_t (consider 32 bit, or arches like cheri etc). 

As a result, I think this may actually be a correct error because the assumption you are making here is incorrect. Reading this I actually have some concerns about the use of atomics to manipulate the linked list because that's race-condition central, and I think i'd want to double check it to be sure it's valid. 

It's also raised in the gcc manual:

```
These functions are implemented in terms of the ‘__atomic’ builtins (see [__atomic Builtins](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html#g_t_005f_005fatomic-Builtins)). They should not be used for new code which should use the ‘__atomic’ builtins instead.
```

https://gcc.gnu.org/onlinedocs/gcc/_005f_005fsync-Builtins.html

So I think you actually need to rework this to remove the __sync calls, and use the __atomic calls. I think you also need to set the ordering to SEQ_CST unless you are willing to do a more thorough examination of this on relaxed ordering cpus (x86_64 is strong ordering, you need aarch64 to test this properly). 

Generally my instinct is that the moment you reach for __atomic, you are probably about to make a large mistake.  🙃 It's very complicated and subtle to handle correctly. You may genuinely be better of wrapping with a lock instead to prevent errors here. 


So I think there are actually bigger potential thread safety issues here in this code.

**Comment by progier389** [comment]
Hum,
I think you are wrong:
[1] The error message you get is complaining about: It does not complain about the fact 
      pointer is cast to an integer but:
        passing 'int64_t' (aka 'long') to parameter of type 'void *'
      (i.e the fact that we are passing an integer as argument while a pointer is expectedO
[2] You do not need that the size exactly match you just need that the integer in which you store the pointer is wider than the 
     pointer size and as far as I remember the C standard (at least until C99) that explicitly mention that sizeof (long) should be >= to sizeof (void*) so that you could cast a pointer to a long (and to a long long)

Anyway, I agree with you using __atomic_compare_exchange should be more portable (furthermore it avoid the cast
  issue).  According to https://gcc.gnu.org/wiki/Atomic/GCCMM/AtomicSync I think that __ATOMIC_ACQ_REL should be enough (as it insure that non atomic variable are stored) but I am fine with __ATOMIC_SEQ_CST too.
  
I guess that we could try:
     __atomic_compare_exchange(addr, old, new, 1, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE);
     __atomic_compare_exchange(addr, old, new, 0, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE);
     __atomic_compare_exchange(addr, old, new, 1, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
     __atomic_compare_exchange(addr, old, new, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
As the cas is used in a loop I do not think that the weak flags really matters 
  anyway I do not expect any difference on x64  

I never have much trouble with atomic operation but I must says that I only have mostly used them on RS6K and x64 cpus
(They are routinely used in AIX kernel code because there is quite a performance difference compared to using mutex 
   on large SMP and NUMA machines) (Probably because synchronization occurs both when locking and when unlocking the mutex while it occurs only once in a CAS)
 That said I have almost no experience about ARM and that may be where there is trouble with atomic operations.
  On last resort we could always implement a trade-off and use lock for ARM and atomic operation on Intel ...

**Comment by progier389** [comment]
OK, I will go for atomic operation on x64 and with a mutex on the other architecture

**Comment by Firstyear** [comment]
I think you should just use a mutex on x86_64 as well, because there are still subtleties there. Atomics are fine as a counter or a ref count with correct flags, but not for updating linked list elements. There are too many ways this can go wrong. Just use a mutex please.

**Comment by progier389** [comment]
More precisely it is fixed by [PR 5498](https://github.com/389ds/389-ds-base/pull/5498) (The queues handling changed and is now using mutex instead of atomic CAS.)
